### ISSUE TITLE
ParsingException encountered when DataFrame contains variable name `'date'`

### ISSUE THREAD

**Issue by flcong** [nils-braun/dask-sql#189]
Code:
```python
import pandas as pd
import numpy as np
from dask.distributed import Client
from dask_sql import Context
client = Client()
cont = Context()

df1 = pd.DataFrame({
    'date': pd.date_range(pd.Timestamp('2021-01-01'), pd.Timestamp('2021-01-10')),
    'var1': np.ones(10)})
df2 = pd.DataFrame({
    'startdate': [pd.Timestamp('2020-12-30'), pd.Timestamp('2021-01-09')],
    'enddate': [pd.Timestamp('2020-01-03'), pd.Timestamp('2021-01-20')],
    'var2': np.array([2.0, 3.0])})

cont.create_table('df1', df1)
cont.create_table('df2', df2)
```
where `df1` is as follows:
```
        date  var1
0 2021-01-01   1.0
1 2021-01-02   1.0
2 2021-01-03   1.0
3 2021-01-04   1.0
4 2021-01-05   1.0
5 2021-01-06   1.0
6 2021-01-07   1.0
7 2021-01-08   1.0
8 2021-01-09   1.0
9 2021-01-10   1.0
```
and `df2` is as follows:
```
   startdate    enddate  var2
0 2020-12-30 2020-01-03   2.0
1 2021-01-09 2021-01-20   3.0
```

Then, the following code raises ParsingException:
```python
df3 = cont.sql(
    """select a.*, b.var2
    from df1 a left join df2 b
    on b.startdate<=a.date and a.date<=b.enddate""").compute()
```
Output:
```python
Traceback (most recent call last):

  File "<ipython-input-16-df0e34857e3f>", line 13, in <module>
    df3 = cont.sql(

  File "C:\Programs\miniconda3\lib\site-packages\dask_sql\context.py", line 394, in sql
    rel, select_names, _ = self._get_ral(sql)

  File "C:\Programs\miniconda3\lib\site-packages\dask_sql\context.py", line 641, in _get_ral
    raise ParsingException(sql, str(e.message())) from None

ParsingException: Can not parse the given SQL: Encountered ". date" at line 3, column 22.
Was expecting one of:
    <EOF> 
    "ORDER" ...
    "LIMIT" ...
    "OFFSET" ...
    "FETCH" ...
    "NATURAL" ...
    "JOIN" ...
    "INNER" ...
    "LEFT" ...
    "RIGHT" ...
    "FULL" ...
    "CROSS" ...
    "," ...
    "OUTER" ...
    "WHERE" ...
    "GROUP" ...
    "HAVING" ...
    "WINDOW" ...
    "UNION" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "." <IDENTIFIER> ...
    "." <HYPHENATED_IDENTIFIER> ...
    "." <QUOTED_IDENTIFIER> ...
    "." <BACK_QUOTED_IDENTIFIER> ...
    "." <BRACKET_QUOTED_IDENTIFIER> ...
    "." <UNICODE_QUOTED_IDENTIFIER> ...
    "." ...
    "NOT" ...
    "IN" ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    "=" ...
    "<>" ...
    "!=" ...
    "BETWEEN" ...
    "LIKE" ...
    "SIMILAR" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "%" ...
    "||" ...
    "AND" ...
    "OR" ...
    "IS" ...
    "MEMBER" ...
    "SUBMULTISET" ...
    "CONTAINS" ...
    "OVERLAPS" ...
    "EQUALS" ...
    "PRECEDES" ...
    "SUCCEEDS" ...
    "IMMEDIATELY" ...
    "MULTISET" ...
    "[" ...
    "FORMAT" ...
    "." "*" ...
    "(" ...

The problem is probably somewhere here:

	select a.*, b.var2
	    from df1 a left join df2 b
	    on b.startdate<=a.date and a.date<=b.enddate
	                     ^
```
Later, I find out that the problem is the variable name `'date'` in `df1`. If I change it to others (e.g. `dated`), the problem disappear.

**Comment by nils-braun** [comment]
Hi @flcong 
Thanks for the big report and the nice reproducible example. The problem is, that `date` is a SQL keyword. Therefore you need to add quotes to it to make SQL understand it as a column - at least in the SQL dialect used by Dask-SQL. You can check out [the documentation](https://dask-sql.readthedocs.io/en/latest/pages/sql.html#general) on quotes, which has accidentally even `date` as an example for this.

**Comment by flcong** [comment]
Thank you! I come from SAS SQL, so I am not aware of this issue.
