### ISSUE TITLE
Issue Importing Dask-Sql

### ISSUE THREAD

**Issue by timhdesilva** [nils-braun/dask-sql#196]
Hi,

I just purchased a new computer (making the switch from WIndows to Mac) and am looking to use dask-sql as I do on Windows. I first installed ``dask`` with ``python3 -m pip install "dask"`` in my terminal, and then installed ``dask-sql`` with ``python3 -m pip install "dask-sql"``. The problem is that when I try to run:
```from dask_sql import Context()```
I get the following error
```
Traceback (most recent call last):

  File "<ipython-input-2-498d7bb26d1f>", line 1, in <module>
    from dask_sql import Context

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/dask_sql/__init__.py", line 2, in <module>
    from .cmd import cmd_loop

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/dask_sql/cmd.py", line 8, in <module>
    from dask.distributed import Client

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/dask/distributed.py", line 3, in <module>
    from distributed import *

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/distributed/__init__.py", line 7, in <module>
    from .actor import Actor, ActorFuture

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/distributed/actor.py", line 6, in <module>
    from .client import Future, default_client

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/distributed/client.py", line 30, in <module>
    from dask.compatibility import apply

ImportError: cannot import name 'apply' from 'dask.compatibility' (/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/dask/compatibility.py)
```

**Comment by nils-braun** [comment]
Hi @timhdesilva !
Thanks for your report! Unfortunately I can not reproduce myself (I do not own a Mac...),   but is this only a problem with dask-sql or also with dask alone? Could you try to run a `from dask.distributed import Client`? It might just be some incompatible versions of dask and distributed (I currently assume it is unrelated to dask-sql).

Can you also print the output of `pip list` here? Thanks!

**Comment by timhdesilva** [comment]
Thanks for the great response, as usual @nils-braun. I wouldn't have thought to realize it had to do with ``dask`` and ``distributed``. Was able to fix it by running ``pip uninstall`` on ``dask`` and using ``pip install dask==XX``, where ``XX`` is the version of ``distributed``. No issues now!

**Comment by nils-braun** [comment]
Glad it works now!
